FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY database ./database
COPY src ./src
COPY docker-entrypoint.dev.sh ./

RUN sed -i 's/\r$//' docker-entrypoint.dev.sh && chmod +x docker-entrypoint.dev.sh && mkdir -p uploads
